### ISSUE TITLE
Integrate Tailwind Merge gem for efficient class management

### ISSUE THREAD

**Issue by iseth** [PhlexUI/phlex_ui#63]
We need to integrate the Tailwind Merge gem into our project to efficiently manage and merge Tailwind CSS classes without style conflicts. This gem is particularly useful when working with component-based UI renderers like ViewComponent or Ariadne, where overriding styles can be challenging due to CSS cascade behavior.

What Tailwind Merge does:
- Provides a utility function to merge Tailwind CSS classes efficiently
- Resolves conflicts between classes, ensuring intended styles are applied
- Maintains non-conflicting classes

Example use case:
When we have a component with base classes and want to override some styles:

```ruby
# Current behavior
render(ConfirmEmailComponent.new(class: "p-5"))
# Result: "border rounded px-2 py-1 p-5" (p-5 is ignored due to CSS cascade)

# Desired behavior with Tailwind Merge
@merger = TailwindMerge::Merger.new
@merger.merge("border rounded px-2 py-1 p-5")
# Result: "border rounded p-5"
```

Gem url:
https://github.com/gjtorikian/tailwind_merge

**Comment by cirdes** [comment]
closed by #67
