### ISSUE TITLE
Why move everything to Kits?

### ISSUE THREAD

**Issue by johnmcdowall** [PhlexUI/phlex_ui#68]
Seems a bit premature to do this given that it's an experimental feature: 

```
⚠️ [WARNING] Phlex::Kit is experimental and may be removed from future versions of Phlex.
```

Also, there's no documentation on the site Phlex site iteself about Kits.

**Comment by iseth** [comment]
Much cleaner syntax and it's not experimental anymore 😃

https://github.com/phlex-ruby/phlex/releases/tag/1.11.0
