### ISSUE TITLE
Stop default component override

### ISSUE THREAD

**Issue by iseth** [PhlexUI/phlex_ui#82]
After installing / ejecting a component into my rails app with:
```bash
bin/rails g rbui:generate button
```

when I call:
```ruby
RBUI.Button {"Click here"}
```

I would like to be able to do:
```ruby
RBUI.Button(override: true) {"Click here"}
```
Which would override the "override" from the eject/installed component. This would allow to still use the gem component when the component has been installed.

**Comment by thedumbtechguy** [comment]
The naming might be confusing.

**Comment by iseth** [comment]
yeah good point. I'm changing my focus now lol
